// Branded PDF export via a print window (crisp, selectable text, no heavy deps).
// Opens a styled MadeEA document and triggers the browser's print → Save as PDF.
import { sanitizeHtml } from "@/lib/sanitize";

function escapeHtml(s: string) {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]!));
}

export function exportToPdf(title: string, bodyHtml: string) {
  const w = window.open("", "_blank", "width=820,height=920");
  if (!w) {
    alert("Allow pop-ups for this site to export PDF.");
    return;
  }
  const logo = `${window.location.origin}/logo.png`;
  // window.open("") yields a SAME-ORIGIN document, so anything injected here runs
  // with access to this origin's session. Callers already pass sanitized HTML;
  // re-purify so a future caller can't reopen the hole from a distance.
  const safeBody = sanitizeHtml(bodyHtml);
  w.document.write(`<!doctype html>
<html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title>
<style>
  *{box-sizing:border-box}
  body{font-family:-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:#1a2330;margin:0}
  .brand{background:#09141f;padding:16px 32px;display:flex;align-items:center;justify-content:space-between}
  .brand img{height:22px}
  .brand .tag{color:#fd5812;font-size:11px;letter-spacing:.12em;text-transform:uppercase;font-weight:600}
  .accent{height:3px;background:#fd5812}
  .doc{max-width:720px;margin:0 auto;padding:36px 32px;line-height:1.6;font-size:14px}
  .doc h1{font-size:22px;color:#0e1f2f;margin:.2em 0 .4em}
  .doc h2{font-size:18px;color:#0e1f2f;margin:1.2em 0 .4em;border-bottom:1px solid #e5e9ee;padding-bottom:4px}
  .doc h3{font-size:15px;color:#0e1f2f;margin:1em 0 .3em}
  .doc p{margin:.6em 0}
  .doc ul,.doc ol{padding-left:22px;margin:.6em 0}
  .doc table{border-collapse:collapse;width:100%;margin:12px 0}
  .doc th,.doc td{border:1px solid #d8dee6;padding:6px 10px;text-align:left}
  .doc th{background:#f3f5f8}
  .doc code{background:#f3f5f8;padding:1px 4px;border-radius:4px;font-size:.9em}
  .doc blockquote{border-left:3px solid #fd5812;margin:.6em 0;padding-left:12px;color:#55606e}
  .doc hr{border:none;border-top:1px solid #e5e9ee;margin:1em 0}
  footer{color:#8a97a5;font-size:11px;text-align:center;padding:18px;border-top:1px solid #e5e9ee;margin-top:24px}
  @media print{.brand,.accent{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style></head>
<body>
  <div class="brand"><img src="${logo}" alt="MadeEA"/><span class="tag">${escapeHtml(title)}</span></div>
  <div class="accent"></div>
  <main class="doc">${safeBody}</main>
  <footer>Generated by MadeEA · Command Center</footer>
</body></html>`);
  w.document.close();
  // Driven from here rather than an inline <script> in the child: the print
  // window inherits this origin's CSP, and script-src is strict ('self', no
  // 'unsafe-inline'), so an inline script would simply be blocked.
  setTimeout(() => w.print(), 350);
}
